# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthDialog(object):
    def setupUi(self, AuthDialog):
        AuthDialog.setObjectName("AuthDialog")
        AuthDialog.resize(224, 166)
        self.buttonBox = QtWidgets.QDialogButtonBox(AuthDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 130, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.username = QtWidgets.QLabel(AuthDialog)
        self.username.setGeometry(QtCore.QRect(20, 10, 50, 20))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLabel(AuthDialog)
        self.password.setGeometry(QtCore.QRect(20, 40, 51, 21))
        self.password.setObjectName("password")
        self.host = QtWidgets.QLabel(AuthDialog)
        self.host.setGeometry(QtCore.QRect(20, 70, 61, 16))
        self.host.setObjectName("host")
        self.winauth = QtWidgets.QLabel(AuthDialog)
        self.winauth.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.winauth.setText("")
        self.winauth.setObjectName("winauth")
        self.use_winauth = QtWidgets.QCheckBox(AuthDialog)
        self.use_winauth.setGeometry(QtCore.QRect(20, 100, 70, 17))
        self.use_winauth.setObjectName("use_winauth")
        self.username_input = QtWidgets.QLineEdit(AuthDialog)
        self.username_input.setGeometry(QtCore.QRect(100, 10, 113, 20))
        self.username_input.setObjectName("username_input")
        self.host_input = QtWidgets.QLineEdit(AuthDialog)
        self.host_input.setGeometry(QtCore.QRect(100, 70, 113, 20))
        self.host_input.setObjectName("host_input")
        self.password_input = QtWidgets.QLineEdit(AuthDialog)
        self.password_input.setGeometry(QtCore.QRect(100, 40, 113, 20))
        self.password_input.setObjectName("password_input")

        self.retranslateUi(AuthDialog)
        self.buttonBox.accepted.connect(AuthDialog.accept)
        self.buttonBox.rejected.connect(AuthDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AuthDialog)

    def retranslateUi(self, AuthDialog):
        _translate = QtCore.QCoreApplication.translate
        AuthDialog.setWindowTitle(_translate("AuthDialog", "Auth engine"))
        self.username.setText(_translate("AuthDialog", "Username"))
        self.password.setText(_translate("AuthDialog", "Password"))
        self.host.setText(_translate("AuthDialog", "Target host"))
        self.use_winauth.setText(_translate("AuthDialog", "Winauth"))
