# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_table_view = QtWidgets.QTableView(self.centralwidget)
        self.main_table_view.setGeometry(QtCore.QRect(10, 40, 491, 531))
        self.main_table_view.setObjectName("main_table_view")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(510, 460, 311, 111))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 430, 61, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 21))
        self.menubar.setObjectName("menubar")
        self.menuAuth = QtWidgets.QMenu(self.menubar)
        self.menuAuth.setObjectName("menuAuth")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.new_instance_buton = QtWidgets.QAction(MainWindow)
        self.new_instance_buton.setObjectName("new_instance_buton")
        self.menuAuth.addAction(self.new_instance_buton)
        self.menubar.addAction(self.menuAuth.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SQL Tool"))
        self.label.setText(_translate("MainWindow", "SQL Query"))
        self.menuAuth.setTitle(_translate("MainWindow", "Auth"))
        self.new_instance_buton.setText(_translate("MainWindow", "New instance"))
